# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Build and Deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build with Gradle
        run: ./gradlew clean build jib --image=europe-west2-docker.pkg.dev/dev-env-309121/test-repo/kotlin-spring-boot-graphql-ap

#  test:
#    needs: [build]
#    runs-on: ubuntu-latest
#
#    steps:
#      - uses: actions/checkout@v2
#      - name: Set up JDK 11
#        uses: actions/setup-java@v1
#        with:
#          java-version: 11
#      - name: Integration Tests
#        run: mvn -B test --file pom.xml

#  deploy:
#    needs: [build, test]
#    runs-on: ubuntu-latest
#
#    steps:
#      - uses: actions/checkout@v2
#      - uses: google-github-actions/setup-gcloud@master
#        with:
#          version: '290.0.1'
#          project_id: ${{ secrets.GCP_PROJECT_ID }}
#          service_account_key: ${{ secrets.SERVICE_ACCOUNT }}
#          export_default_credentials: true
#
#      - name: GCP Authenticate
#        uses: google-github-actions/setup-gcloud@master
#        with:
#          version: "273.0.0"
#          service_account_key: ${{ secrets.SERVICE_ACCOUNT }}
#
#
#      - name: Set GCP_PROJECT
#        env:
#          GCP_PROJECT: ${{ secrets.PROJECT_ID }}
#        run: gcloud --quiet config set project ${GCP_PROJECT}
#
#      - name: Deploy to GAE
#        run: mvn -B -DskipTests clean package appengine:deploy --file pom.xml



